# Cloudflare Tunnel Yapılandırması
# NotebookPro - notebookpro.siyahkare.com

tunnel: 2b6f3c08-cca1-40f8-8659-8a11903f6b40
credentials-file: /Users/onur/.cloudflared/2b6f3c08-cca1-40f8-8659-8a11903f6b40.json

ingress:
  # Ana domain - notebookpro.siyahkare.com
  - hostname: notebookpro.siyahkare.com
    service: http://localhost:4173
    originRequest:
      noTLSVerify: true
  
  # Catch-all rule (zorunlu)
  - service: http_status:404

